neword/urls.py
from django.urls import path
from . import views
from .models import *

app_name = 'neword'

urlpatterns = [ 
	path('',views.Home, name='home'),
	path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('text_trans/', views.text_trans, name='text_trans'),
    path('upload/', views.upload_file, name='file_trans'),
    path('delete_word/<int:word_id>/', views.delete_word, name='delete_word'),
    path('edit_word/<int:pk>/', views.edit_word, name='edit_word'),
    path('get_data/', views.get_data, name='get_data'),
]

oneword/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('neword.urls',namespace='neword')),
    path('accounts/', include('django.contrib.auth.urls')),
]

neword/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Words(models.Model):
    word = models.CharField(max_length=255)
    translation = models.CharField(max_length=255)
    date_added = models.DateTimeField(auto_now_add=True)

class UserWords(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    word = models.CharField(max_length=255)
    translation = models.CharField(max_length=255)
    date_added = models.DateTimeField(auto_now_add=True)

class UserWordsNums(models.Model):
    quantity = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

neword/forms.py
# forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import UserWords

class SignupForm(UserCreationForm):
    email = forms.EmailField(required=True)
    
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

class FileUploadForm(forms.Form):
    file = forms.FileField(required= True,label='Select a file',widget=forms.FileInput(attrs={'accept': '.docx,.pdf,.txt'}))


class EditWordForm(forms.ModelForm):
    class Meta:
        model = UserWords
        fields = ('word', 'translation')
        labels = {
            'word': 'Word',
            'translation': 'Translation',
        }

neword/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login
from django.shortcuts import render, redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from .forms import FileUploadForm,EditWordForm 
from googletrans import Translator
from .models import Words,UserWords,UserWordsNums
import re
from datetime import datetime
from django.http import JsonResponse, HttpResponseForbidden
from django.contrib import messages
from django.urls import reverse
from django.forms.models import model_to_dict
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt

prev_total_words = 0 # holds total words quantity of user before translation
new_words_counter = 0 # counts new words numbers
def Home(request):
    try:
        global total_words
        total_words = UserWords.objects.filter(user=request.user).count()
    except Exception as e:
        print('bomadi')
    return render(request, 'home.html')

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
    else:
        form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': form})

def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            auth_login(request, user)
            return redirect('neword:home')
    else:
        form = AuthenticationForm()
    return render(request, 'registration/login.html', {'form': form})

def logout_view(request):
    logout(request)
    return redirect('neword:home')

def profile(request):
    global total_words,new_words_counter
    total_words = UserWords.objects.filter(user=request.user).count()
    user = request.user
    words_list = UserWords.objects.filter(user=request.user).order_by('-date_added')
    total = total_words
    # create a dictionary to pass to the template
    context = {
        'words_list': words_list,
        'user': user,
        'total_words':total,
        'new_added':new_words_counter,
    }
    new_words_counter = 0
    return render(request, 'registration/profile.html', context)	

@login_required
def text_trans(request):
    if request.method == 'POST':
        count = 0
        # Logic to handle form submission goes here
        global new_words_counter
        percent = 0
        user = request.user
        text = request.POST.get('text')
        words = purify_words(text.split(' '))
        translator = Translator()
        user_words = UserWords.objects.filter(user=request.user).values_list('word', flat=True)
        user_words_list = list(user_words)
        new_words_counter = newbies(words,user_words_list)
        new_words = new_word(words,user_words_list)
        for word in new_words:
            try:
                translation = translator.translate(word, dest='uz').text
                UserWords.objects.create(word=word.lower(), translation=translation.lower(),user=user,date_added=datetime.now())
                user_words_list.append(word.lower())
            except Exception as e:
                print('No words')
 
        return redirect('neword:profile')
    else:
        return render(request, 'text_trans.html')

def upload_file(request):
    if request.method == 'POST':
        form = FileUploadForm(request.POST, request.FILES)
        if form.is_valid():
            # Do something with the uploaded file
            uploaded_file = request.FILES['file']
            # Process the file and find new words
            # ...
            return render(request, 'file_upload_success.html')
    else:
        form = FileUploadForm()
    return render(request, 'file_trans.html', {'form': form})

@login_required
def delete_word(request, word_id):
    word = get_object_or_404(UserWords, id=word_id, user=request.user)
    word.delete()
    return JsonResponse({'success': True})

@csrf_exempt
def edit_word(request, pk):
    if request.method == 'POST':
        word = get_object_or_404(UserWords, pk=pk)
        word.word = request.POST.get('word')
        word.translation = request.POST.get('translation')
        word.save()
        data = {
            'success': True,
            'word': {
                'word': word.word,
                'translation': word.translation,
            },
        }
        return JsonResponse(data)

def purify_words(words):
    clean_words = [re.sub(r'\W+', '', word) for word in words]
    return clean_words

def get_data(request,data):
    return JsonResponse(data)


def newbies(words,user_words_list):
    count = 0
    new_words = []
    for i in words:
        if i not in user_words_list:
            count+=1
            new_words.append(i)
    return count

def new_word(words,user_words_list):
    new_words = []
    count = 0
    for i in words:
        count += 1
        if not i in user_words_list and not i in new_words:
            new_words.append(i)
    print(len(user_words_list),count)
    return new_words

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}My Website{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'neword:home' %}">My Website</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'neword:home' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'neword:file_trans' %}">File</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'neword:text_trans' %}">Text</a>
                        </li>
                        {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'neword:profile' %}">Profile</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'neword:logout' %}">Logout</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'neword:login' %}">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'neword:signup' %}">Sign Up</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main class="container mt-5">
        {% block content %}{% endblock %}
    </main>
    <footer class="bg-light mt-5 py-3 fixed-bottom">
        <div class="container text-center">
            <p>&copy; 2023 Rakhimov Fazliddin</p>
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.3/umd/popper.min.js"></script>
    <script type="text/javascript" src="{% static 'base.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js"></script>
</body>
</html>

templates/file_trans.html
{% extends 'base.html' %}

{% block title %}Find New words from file{% endblock %}

{% block content %}

  <div class="container">
    <form id="translate-form" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" id="translate-button" class="btn btn-primary">Upload</button>
    </form>
    <!-- Modal for progress bar -->
    <div class="modal fade" id="progress-modal" tabindex="-1" role="dialog" aria-labelledby="progress-modal-label" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="progress-modal-label">Translation Progress</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <div class="progress">
              <div class="progress-bar" role="progressbar" style="width: 0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script>
    // show progress bar modal on form submit
    $('#translate-form').submit(function(event) {
      event.preventDefault();
      $('#progress-modal').modal('show');

      var form = $(this);
      var url = form.attr('action');
        $.ajax({
        url: url,
        method: 'GET',
        dataType: 'json',
        success: function(response) {
          var progress = response.progress;
          if (progress === 100) {
            // Hide the progress bar when progress reaches 100%
            $('.progress-bar').fadeOut();
          } else {
            // Update the progress bar and show it
            $('.progress-bar').width(progress + '%');
            $('.progress-bar').text(progress + '%');
            $('.progress-bar').fadeIn();
            // Check progress again after 1 second
            setTimeout(checkProgress, 1000);
          }
        },
        error: function(response) {
          console.log(response.responseText);
        }
      });
    });
  </script>
{% endblock %}

templates/file_upload_success.html
{% extends 'base.html' %}

{% block title %}success!!!{% endblock %}

{% block content %}
    <h1>File Upload Success!!!
    </h1>
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h1 class="text-center">Welcome to our Text Translation Website</h1>
            </div>
        </div>

        <div class="row justify-content-center mt-3">
            <div class="col-12 col-md-6">
                <div id="data-container"></div>
            </div>
        </div>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
{% endblock %}

templates/text_trans.html
{% extends 'base.html' %}

{% block title %}Find New words from text{% endblock %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-md-8 offset-md-2">
        <h2 class="text-center">Enter text</h2>
        <form method="post">
          {% csrf_token %}
          <div class="form-floating mb-3">
            <textarea class="form-control" name="text" placeholder=" " id="text" rows="5"></textarea>
            <label for="text">Text:</label>
          </div>
          <button type="submit" class="btn btn-primary btn-block mt-3">Submit</button>
        </form>
      </div>
    </div>
  </div>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
{% endblock %}